In [3]:
import numpy as np
from sklearn.neighbors import radius_neighbors_graph, KDTree
import chainer
import chainer.functions as F
import glob
import struct
import cupy
from chainer import cuda
import time

In [4]:
DATA_PATH = '/home/evan/Data/nbody_simulations/N_{0}/DM*/{1}_dm.z=0{2}000'
#=============================================================================
# Data utils
#=============================================================================
def read_sim(file_list, n_P):
    """ reads simulation data from disk and returns

    Args:
        file_list: (list<str>) paths to files
        n_P: (int) number of particles base (n_P**3 particles)
    """
    num_particles = n_P**3
    dataset = []
    for file_name in file_list:
        this_set = []
        with open(file_name, "rb") as f:
            for i in range(num_particles*6):
                s = struct.unpack('=f',f.read(4))
                this_set.append(s[0])
        dataset.append(this_set)
    dataset = np.array(dataset).reshape([len(file_list),num_particles,6])  
    return dataset

def load_datum(n_P, redshift, normalize_data=False):
    """ loads two redshift datasets from proper data directory

    Args:
        redshift: (float) redshift
        n_P: (int) base of number of particles (n_P**3 particles)
    """
    N_P = 10000 if n_P == 32 else 1000
    glob_paths = glob.glob(DATA_PATH.format(N_P, 'xv', redshift))
    X = read_sim(glob_paths, n_P)
    if normalize_data:
        X = normalize(X)
    return X

def normalize(X_in):
    """ Normalize features
    coordinates are rescaled to (0,1)
    velocities normalized by mean/std    
    """
    x_r = np.reshape(X_in, [-1,6])
    coo, vel = np.split(x_r, [3], axis=-1)
    coo_min = np.min(coo, axis=0)
    coo_max = np.max(coo, axis=0)
    #coo_mean, coo_std = np.mean(coo,axis=0), np.std(coo,axis=0)
    #x_r[:,:3] = (x_r[:,:3] - coo_mean) / (coo_std)
    vel_mean = np.mean(vel, axis=0)
    vel_std  = np.std( vel, axis=0)
    x_r[:,:3] = (x_r[:,:3] - coo_min) / (coo_max - coo_min)
    x_r[:,3:] = (x_r[:,3:] - vel_mean) / vel_std
    X_out = np.reshape(x_r,X_in.shape).astype(np.float32) # just convert to float32 here
    return X_out

In [5]:
'''
Data
'''
num_particles = 16
zX = 0.6
X = load_datum(num_particles, zX, normalize_data=True)
N = X.shape[0]

In [ ]:
class DensityNN():
    def __init__(self, X_in, rad):
        self.rad = rad
        
    def get_adjacency_list(self, X_in):
        rad = self.rad
        X

In [5]:
'''
Density stuff
LOOK AT sklearn.neighbors module,
 - KDTree
 - Ball tree
 - radius neighbors
'''
rad = 0.01
x = X[0,:,:3]

In [6]:
graph = radius_neighbors_graph(x[:,:3], rad, include_self=True)
kdtree = KDTree(x)
coograph = graph.tocoo()
indptr  = graph.indptr
data    = graph.data
indices = graph.indices
print('graph.shape{} data.shape: {}, indices.shape: {}, indptr.shape: {}'.format(graph.shape, data.shape, indices.shape, indptr.shape))

graph.shape(4096, 4096) data.shape: (4876,), indices.shape: (4876,), indptr.shape: (4097,)


In [106]:
print(kdtree.query_radius(x, r=0.01))

[array([0]) array([1]) array([2]) ..., array([4093]) array([4094])
 array([4095])]


In [156]:
def make_kdtree(x, leaf_size):
    xflat = np.reshape(x, (-1, x.shape[-1]))
    t0 = time.time()
    kdtree = KDTree(xflat, leaf_size=leaf_size)
    print('{} time: {}'.format(leaf_size, time.time() - t0))
    return kdtree

x8 = X[:8]
kdtree40 = make_kdtree(x8, leaf_size=4096)

4096 time: 0.0036771297454833984


In [ ]:
class DensityNN():
    def __init__(self, X_in, rad, leaf_size=40):
        self.rad = rad
        mb_size, N, D = X_in.shape
        self.batch_idx = [i*N for i in range(mb_size)]
        self.kdtree = self.create_kdtree(X_in, leaf_size)
    
    def create_kdtree(self, X_in, leaf_size):
        r = self.rad
        mb_size, N, D = X_in.shape
        x = np.reshape(X_in, (-1, D))
        kdtree = KDTree(x, leaf_size=leaf_size)
        
        

In [157]:
x.shape

(4096, 3)

In [162]:
x1605n = x[kdtree.query_radius(x[[1605]], r=0.01).item()]
kdtree.query_radius(x, r=0.01)

array([array([0]), array([1]), array([2]), ..., array([4093]),
       array([4094]), array([4095])], dtype=object)

In [163]:
a = np.random.rand(4000, 3)

In [170]:
radius_neighbors_graph(a, 0.01, include_self=True).nnz

4078

In [114]:
np.random.seed(0)
Y = np.random.random((10,3))
tree = KDTree(Y, leaf_size=2)
print(tree.query_radius(Y[[0]], r=0.3, count_only=True))
ind, dist = tree.query_radius(Y[[0]], r=0.3, return_distance=True)
print(ind)
print(dist)

[3]
[array([3, 0, 1])]
[array([ 0.19662693,  0.        ,  0.29473397])]


In [88]:
print('ROW: IND, DATA')
for i in range(x.shape[0]):
    j,k = indptr[i], indptr[i+1]
    cur_ind = indices[j:k]
    cur_data = data[j:k]
    print('{}: {}, {}'.format(i, cur_ind, cur_data))
    

ROW: IND, DATA
0: [0], [ 1.]
1: [1], [ 1.]
2: [2], [ 1.]
3: [3], [ 1.]
4: [4], [ 1.]
5: [261 277   5], [ 1.  1.  1.]
6: [6], [ 1.]
7: [7], [ 1.]
8: [ 8 24], [ 1.  1.]
9: [9], [ 1.]
10: [10], [ 1.]
11: [11], [ 1.]
12: [12 13], [ 1.  1.]
13: [12 13], [ 1.  1.]
14: [14], [ 1.]
15: [15], [ 1.]
16: [16], [ 1.]
17: [17], [ 1.]
18: [18], [ 1.]
19: [19], [ 1.]
20: [ 20 517], [ 1.  1.]
21: [ 21 278], [ 1.  1.]
22: [262  22], [ 1.  1.]
23: [23], [ 1.]
24: [ 8 24], [ 1.  1.]
25: [25], [ 1.]
26: [26], [ 1.]
27: [27], [ 1.]
28: [29 28], [ 1.  1.]
29: [29 28], [ 1.  1.]
30: [30], [ 1.]
31: [31], [ 1.]
32: [32], [ 1.]
33: [33], [ 1.]
34: [34], [ 1.]
35: [35], [ 1.]
36: [36], [ 1.]
37: [37], [ 1.]
38: [38], [ 1.]
39: [39], [ 1.]
40: [40], [ 1.]
41: [41], [ 1.]
42: [42], [ 1.]
43: [43], [ 1.]
44: [44], [ 1.]
45: [45], [ 1.]
46: [46], [ 1.]
47: [47], [ 1.]
48: [48], [ 1.]
49: [49], [ 1.]
50: [50], [ 1.]
51: [51], [ 1.]
52: [52], [ 1.]
53: [53], [ 1.]
54: [70 54], [ 1.  1.]
55: [55], [ 1.]
56: [56], [ 1.

1297: [1297], [ 1.]
1298: [1298], [ 1.]
1299: [1299], [ 1.]
1300: [1300], [ 1.]
1301: [1301], [ 1.]
1302: [1302], [ 1.]
1303: [1303], [ 1.]
1304: [1304], [ 1.]
1305: [1305], [ 1.]
1306: [1306], [ 1.]
1307: [1307], [ 1.]
1308: [1564 1308], [ 1.  1.]
1309: [1309], [ 1.]
1310: [1310], [ 1.]
1311: [1311], [ 1.]
1312: [1312], [ 1.]
1313: [1313], [ 1.]
1314: [1314], [ 1.]
1315: [1315], [ 1.]
1316: [1316 1556], [ 1.  1.]
1317: [1317 1573], [ 1.  1.]
1318: [1318], [ 1.]
1319: [1319], [ 1.]
1320: [1320], [ 1.]
1321: [1321], [ 1.]
1322: [1322], [ 1.]
1323: [1323], [ 1.]
1324: [1324], [ 1.]
1325: [1325], [ 1.]
1326: [1326], [ 1.]
1327: [1327], [ 1.]
1328: [1328], [ 1.]
1329: [1329], [ 1.]
1330: [1330], [ 1.]
1331: [1331], [ 1.]
1332: [1588 1332], [ 1.  1.]
1333: [1333], [ 1.]
1334: [1334], [ 1.]
1335: [1335], [ 1.]
1336: [1336], [ 1.]
1337: [1337], [ 1.]
1338: [1339 1338], [ 1.  1.]
1339: [1339 1356 1338 1099], [ 1.  1.  1.  1.]
1340: [1340], [ 1.]
1341: [1341], [ 1.]
1342: [1342], [ 1.]
1343: [1

2639: [2639], [ 1.]
2640: [2640], [ 1.]
2641: [2641], [ 1.]
2642: [2642], [ 1.]
2643: [2643], [ 1.]
2644: [2628 2644], [ 1.  1.]
2645: [2645], [ 1.]
2646: [2646], [ 1.]
2647: [2647], [ 1.]
2648: [2648], [ 1.]
2649: [2649], [ 1.]
2650: [2650], [ 1.]
2651: [2651], [ 1.]
2652: [2652], [ 1.]
2653: [2653], [ 1.]
2654: [2654], [ 1.]
2655: [2655], [ 1.]
2656: [2656], [ 1.]
2657: [2657], [ 1.]
2658: [2658], [ 1.]
2659: [2659], [ 1.]
2660: [2660], [ 1.]
2661: [2661 2390], [ 1.  1.]
2662: [2662], [ 1.]
2663: [2663], [ 1.]
2664: [2664], [ 1.]
2665: [2665], [ 1.]
2666: [2666], [ 1.]
2667: [2667], [ 1.]
2668: [2668], [ 1.]
2669: [2669], [ 1.]
2670: [2670], [ 1.]
2671: [2671], [ 1.]
2672: [2672], [ 1.]
2673: [2673], [ 1.]
2674: [2674], [ 1.]
2675: [2675], [ 1.]
2676: [2676], [ 1.]
2677: [2677], [ 1.]
2678: [2678], [ 1.]
2679: [2679], [ 1.]
2680: [2680], [ 1.]
2681: [2681], [ 1.]
2682: [2682], [ 1.]
2683: [2683], [ 1.]
2684: [2684], [ 1.]
2685: [2685], [ 1.]
2686: [2686], [ 1.]
2687: [2687], [ 1.]
26

3893: [3893], [ 1.]
3894: [3894], [ 1.]
3895: [3895 3879 3911], [ 1.  1.  1.]
3896: [3896], [ 1.]
3897: [3881 3897 3641 3642 3898], [ 1.  1.  1.  1.  1.]
3898: [3881 3897 3641 3642 3898 3625], [ 1.  1.  1.  1.  1.  1.]
3899: [3899], [ 1.]
3900: [3900], [ 1.]
3901: [3933 3901], [ 1.  1.]
3902: [3902], [ 1.]
3903: [3903], [ 1.]
3904: [3904], [ 1.]
3905: [3905], [ 1.]
3906: [3906 3922], [ 1.  1.]
3907: [3907], [ 1.]
3908: [3908], [ 1.]
3909: [3909], [ 1.]
3910: [3910], [ 1.]
3911: [3895 3879 3911], [ 1.  1.  1.]
3912: [3912], [ 1.]
3913: [3913], [ 1.]
3914: [3914 3658], [ 1.  1.]
3915: [3915], [ 1.]
3916: [3916 3660], [ 1.  1.]
3917: [3917 3933], [ 1.  1.]
3918: [3661 3918], [ 1.  1.]
3919: [3919], [ 1.]
3920: [3920], [ 1.]
3921: [3937 3921], [ 1.  1.]
3922: [3906 3922], [ 1.  1.]
3923: [3923], [ 1.]
3924: [3924], [ 1.]
3925: [3925], [ 1.]
3926: [3926], [ 1.]
3927: [3927], [ 1.]
3928: [3928], [ 1.]
3929: [3929], [ 1.]
3930: [3930], [ 1.]
3931: [3931], [ 1.]
3932: [3932], [ 1.]
3933: [3917

In [91]:
ptr1605, ptr1606 = indptr[1605], indptr[1606]

In [96]:
xvar = chainer.Variable(x)

In [34]:
graph_arr = graph.toarray()
summed = np.sum(graph_arr, axis=-1)
graph_div = graph_arr / summed
graph_added = np.matmul(graph_arr, x)

In [24]:
selected_graph = np.matmul(graph_div, x)

In [30]:
inds_all = indices[indptr[:-1]]
data_all = data[indptr[:-1]]
data_div =

In [21]:
selected_csr = x[inds_all]

In [38]:
def csr_select_mean(csr, x):
    y = np.copy(x)
    N = x.shape[0]
    for i in range(N):
        j, k = csr.indptr[i], csr.indptr[i+1]
        cur_ind = csr.indices[j:k]
        num_ind = cur_ind.shape[0]
        y[i] = np.mean(y[cur_ind], axis=0)
    return y

def batch_csr_select_mean(csr, x):
    mb_size, N, D = x.shape
    xflat = np.reshape(x, (-1, D))
    y = np.copy(xflat)
    # csr is flattend dims
    for i in range(xflat.shape[0]):
        a,b = a,b = csr.indptr[i], csr.indptr[i+1]
        cur_ind = csr.indices[a:b]
        y[i] = np.mean(xflat[cur_ind], axis=0)
    return np.reshape(y, (x.shape))

def matmul_select_mean(arr, x):
    summed = np.sum(arr, axis=-1)
    graph_div = graph_arr / summed
    return np.matmul(graph_div, x)

def batch_matmul_select_mean(arr, x):
    mb_size, N, D = x.shape
    xflat = np.reshape(x, (-1, D))
    summed = np.sum(arr, axis=-1)
    #graph_div = graph_arr / summed
    y = np.matmul(arr / summed, xflat)
    return np.reshape(y, (mb_size, N, D))

def kdtree_select_mean(tree, x):
    y = np.copy(x)
    N = x.shape[0]
    for i in range(N):
        n_idx = tree.query_radius(x[[i]], r=0.01)
        y[i] = np.mean(x[n_idx], axis=0)
    return y

In [22]:
x10 = X[:10,:,:3]
x0 = X[0,:,:3]
rad = 0.03
x10flat = np.reshape(x10, (-1, 3))
csr_graph = radius_neighbors_graph(x0, rad, include_self=True)
graph_arr = csr_graph.toarray()
kdtree = KDTree(x10flat,leaf_size=40)

In [23]:
t0 = time.time()
cy = csr_select_mean(csr_graph, x0)
tc_fin = time.time() - t0
tstart_matmul = time.time()
my = matmul_select_mean(graph_arr, x0)
tm_fin = time.time() - tstart_matmul
print('{} {}'.format(tc_fin, tm_fin))

0.06326079368591309 0.08596968650817871


In [24]:
total_time_csr = 0
total_time_mm = 0
for i in range(100):
    x_cur = X[i]
    csr_graph = radius_neighbors_graph(x_cur, rad, include_self=True)
    csr_arr = csr_graph.toarray()
    t0 = time.time()
    cy = csr_select_mean(csr_graph, x_cur)
    total_time_csr += time.time() - t0
    tstart_matmul = time.time()
    my = matmul_select_mean(graph_arr, x_cur)
    total_time_mm += time.time() - tstart_matmul

print('{} {}'.format(total_time_csr, total_time_mm))

4.386312007904053 7.961118221282959


In [39]:
total_time_csr = 0
total_time_mm = 0
mb_size = 8
x_b = X[:8]
x_cur_flat = np.reshape(x_b, (-1, 3))
csr_graph = radius_neighbors_graph(x_cur_flat, rad, include_self=True)
#csr_arr = csr_graph.toarray()
t0 = time.time()
cy = batch_csr_select_mean(csr_graph, x_b)
total_time_csr += time.time() - t0
#tstart_matmul = time.time()
#my = matmul_select_mean(graph_arr, x_cur)
#total_time_mm += time.time() - tstart_matmul

total_time_csr
#print('{} {}'.format(total_time_csr, total_time_mm))

IndexError: index 33278 is out of bounds for axis 0 with size 32768

In [77]:
x3 = x[[3]]
print('x3:{}, {}'.format(x3, np.mean(x3,axis=0)))

x3:[[ 0.2575728   0.0016285   0.07095865]], [ 0.2575728   0.0016285   0.07095865]


In [37]:
for i in range(X.shape[0]):
    rad = 0.03
    neighbors = radius_neighbors_graph(X[i,:,:3], rad, include_self=True)
    
    

array([ 2.24294832,  1.88265181,  2.55108795])

In [41]:
time.time()

1516648670.7555723

In [65]:
for idx in range(ind.shape[0]):
    arr = ind[idx]
    if arr.size > 1:
        print('{} {}'.format(idx, arr))

5 [261 277   5]
8 [ 8 24]
12 [12 13]
13 [12 13]
20 [517  20]
21 [ 21 278]
22 [262  22]
24 [ 8 24]
28 [29 28]
29 [29 28]
54 [70 54]
60 [60 76]
61 [3644   61]
70 [70 54]
76 [60 76]
77 [318  77]
89 [345  89]
112 [3952  112]
122 [377 122]
123 [123 124 637]
124 [123 124]
130 [386 130]
140 [140 141]
141 [140 141]
146 [146 402]
154 [155 154]
155 [155 154]
162 [162 418]
178 [178 434]
183 [695 183 439 423]
184 [440 184]
212 [4052  212 4036]
261 [261 277   5]
262 [262  22]
268 [268 524]
277 [261 277   5]
278 [ 21 278]
283 [539 540 283]
292 [292 804]
293 [293 549]
295 [295 327]
299 [299 300]
300 [299 300]
301 [301 557]
309 [309 565]
310 [310 806 566 822]
312 [328 312]
313 [554 313]
314 [314 329]
315 [315 844 845]
316 [589 573 316]
317 [317 605]
318 [334 318  77]
322 [338 322]
326 [582 326]
327 [295 327]
328 [328 312]
329 [809 314 329]
333 [333 587 571]
334 [334 318]
335 [335 351]
338 [338 322]
345 [345  89]
351 [335 351]
356 [356 612]
377 [377 122]
382 [638 382]
386 [386 130]
402 [146 402]
406 [6

In [29]:
graph.indptr[20:100]

array([ 25,  27,  29,  31,  32,  34,  35,  36,  37,  39,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  67,  68,  69,  70,
        71,  72,  74,  76,  77,  78,  79,  80,  81,  82,  83,  84,  86,
        87,  88,  89,  90,  91,  93,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 108, 109, 110, 111, 112, 113, 114, 115,
       116, 117], dtype=int32)